/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronyzs
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    ArrayList nama = new ArrayList();
    ArrayList pass = new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUser = new javax.swing.JTextField();
        txtPw = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btRegister = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        txtUser.setBackground(new java.awt.Color(101, 75, 175));
        txtUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUser.setText("Username");
        txtUser.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        getContentPane().add(txtUser);
        txtUser.setBounds(110, 160, 210, 40);

        txtPw.setBackground(new java.awt.Color(101, 75, 175));
        txtPw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPw.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPw.setText("password");
        txtPw.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtPw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPwFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPwFocusLost(evt);
            }
        });
        getContentPane().add(txtPw);
        txtPw.setBounds(110, 220, 210, 40);

        btLogin.setBackground(new java.awt.Color(101, 75, 175));
        btLogin.setText("Login");
        btLogin.setBorder(null);
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btLogin);
        btLogin.setBounds(290, 420, 90, 30);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 80, 160, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\ICON\\iconfinder_icons_user2_1564535.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 160, 40, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\ICON\\iconfinder_lock-24_103178.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 220, 40, 40);

        btRegister.setBackground(new java.awt.Color(100, 75, 175));
        btRegister.setText("Register");
        btRegister.setBorder(null);
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btRegister);
        btRegister.setBounds(290, 460, 90, 30);

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\waves-and-forms-purple-background-vector-32732918.jpg")); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(-100, -130, 560, 660);

        setSize(new java.awt.Dimension(416, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        txtUser.setText("");
    }//GEN-LAST:event_txtUserFocusGained

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        if (txtUser.getText().equalsIgnoreCase("")) {
            txtUser.setText("Username");
        }
    }//GEN-LAST:event_txtUserFocusLost

    private void txtPwFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPwFocusGained
        txtPw.setText("");
    }//GEN-LAST:event_txtPwFocusGained

    private void txtPwFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPwFocusLost
        if (txtPw.getText().equals("")) {
            txtPw.setText("Password");
        }
    }//GEN-LAST:event_txtPwFocusLost

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        if (nama.contains(txtUser.getText()) && pass.contains(txtPw.getText())) {
            JOptionPane.showMessageDialog(null, "Login Berhasil!");
            PengisianData a = new PengisianData();
            a.setVisible(true);
            this.setVisible(false);
        } else if (nama.isEmpty() && pass.isEmpty()) {
            JOptionPane.showMessageDialog(null, "anda belum mendaftar!");
        } else {
            JOptionPane.showMessageDialog(null, "Username atau Password yang anda masukan salah!");
        }
    }//GEN-LAST:event_btLoginActionPerformed

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
        this.setVisible(false);
        Register a = new Register();
        a.setVisible(true);
    }//GEN-LAST:event_btRegisterActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPw;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
