/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS;

import javax.swing.JOptionPane;

/**
 *
 * @author Ronyzs
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        REGISTER = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPw = new javax.swing.JTextField();
        txtConfirmPw = new javax.swing.JTextField();
        btReg = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        REGISTER.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        REGISTER.setText("REGISTER");
        getContentPane().add(REGISTER);
        REGISTER.setBounds(100, 60, 200, 50);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 150, 100, 17);

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 210, 110, 17);

        jLabel3.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel3.setText("Confirm Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 270, 190, 17);

        txtUser.setBackground(new java.awt.Color(100, 75, 175));
        getContentPane().add(txtUser);
        txtUser.setBounds(180, 140, 190, 30);

        txtPw.setBackground(new java.awt.Color(100, 75, 175));
        getContentPane().add(txtPw);
        txtPw.setBounds(180, 200, 190, 30);

        txtConfirmPw.setBackground(new java.awt.Color(100, 75, 175));
        getContentPane().add(txtConfirmPw);
        txtConfirmPw.setBounds(180, 260, 190, 30);

        btReg.setBackground(new java.awt.Color(100, 75, 175));
        btReg.setText("Register");
        btReg.setBorder(null);
        btReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegActionPerformed(evt);
            }
        });
        getContentPane().add(btReg);
        btReg.setBounds(283, 443, 90, 30);

        bg.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\waves-and-forms-purple-background-vector-32732918.jpg")); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(-560, -380, 1060, 930);

        setSize(new java.awt.Dimension(416, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegActionPerformed
        Login a = new Login();

        if (txtUser.getText().equalsIgnoreCase("") || txtPw.getText().equalsIgnoreCase("") || txtConfirmPw.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Data harus di isi!");
        }
        else if (txtPw.getText().equals(txtConfirmPw.getText())) {
            a.nama.add(txtUser.getText());
            a.pass.add(txtPw.getText());
            JOptionPane.showMessageDialog(null, "Register berhasil!");
            this.setVisible(false);
            a.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Wrong Password");
        }
    }//GEN-LAST:event_btRegActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel REGISTER;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtConfirmPw;
    private javax.swing.JTextField txtPw;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
